In [ ]:
''' Rathod Shruti A.
     216270307096    '''

'''Write a Pandas program to implement following operation to convert a NumPy array to a Pandas series'''

import numpy as np
import pandas as pd

a = np.array([10,20,30,40,50,60,70,80,90,100])

a1 = pd.Series(a)

print("Pandas series: \n",a1)

In [ ]:
''' Rathod Shruti A.
     216270307096    '''

# Write a Pandas program to implement following operation to convert the first column of a DataFrame as a Series

b = pd.DataFrame({'colors': ['red','pink','white','black','blue'], 'numbers': [1,2,3,4,5]})
print("DataFrame is: \n",b)

b1 = b.iloc[:,0]
print("\nTo convert the first column of a DataFrame as a Series is: \n\n",b1)

In [ ]:
''' Rathod Shruti A.
     216270307096    '''

'''Write a Pandas program to implement following operation to create the mean and standard deviation of the data
of a given Series'''

c = pd.Series([5,10,15,20,25,30])
print("Pandas Series: \n",c)

c1 = c.mean()
print("\nMean is: ",c1)

c2 = c.std()
print("Standard Deviation is: ",c2)

In [ ]:
''' Rathod Shruti A.
     216270307096    '''

'''Write a Pandas program to implement following operation to sort a given Series'''

d = pd.Series([30,20,10,15,5])
print("Orignal Series is: \n",d)

d1 = d.sort_values()
print("\nSorting Series is: \n",d1)